### ISSUE TITLE
Race conditions in tests

### ISSUE THREAD

**Issue by fckt** [nearprotocol/near-bindgen#21]
Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running target/debug/deps/status_message-46714b88b66f7ea3

running 2 tests
test tests::set_get_message ... FAILED
test tests::get_nonexistent_message ... FAILED

failures:

---- tests::set_get_message stdout ----
thread 'tests::set_get_message' panicked at 'Register was expected to have data because we just wrote it into it.', src/libcore/option.rs:1166:5

---- tests::get_nonexistent_message stdout ----
thread 'tests::get_nonexistent_message' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:1084:5
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace.

failures:
    tests::get_nonexistent_message
    tests::set_get_message

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running target/debug/deps/status_message-46714b88b66f7ea3

running 2 tests
test tests::get_nonexistent_message ... ok
test tests::set_get_message ... FAILED

failures:

---- tests::set_get_message stdout ----
thread 'tests::set_get_message' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:1084:5
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace.

**Comment by nearmax** [comment]
We either need to prevent unit tests from running concurrently for rust smart contracts since `env::*` accesses a shared static variable. Or we should put this variable(https://github.com/nearprotocol/near-bindgen/blob/4106110762d284639225a17958a1f87456e36a65/near-bindgen/src/environment/env.rs#L14) behind a `thread_local` https://doc.rust-lang.org/std/macro.thread_local.html

**Comment by fckt** [comment]
fixed by #23
